services:
  postgres-authentication-service:
    container_name: postgres-authentication-service
    hostname: postgres-authentication-service
    image: postgres:alpine3.17
    environment:
      POSTGRES_DB: authentication-service
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - data-authentication-service:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  authentication-service:
    container_name: authentication-service
    hostname: authentication-service
    image: eann1s/authentication-service
    pull_policy: missing
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-authentication-service:5432/authentication-service
    depends_on:
      - postgres-authentication-service

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:jammy
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo:/data/db

volumes:
  data-authentication-service: {}
  mongo: {}
