server:
  port: 8080

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

secret:
  key: ${SECRET_KEY}

services:
  profile:
    name: profile-service
