server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_LOCATION}
          searchPaths: '{application}'
          default-label: main
          timeout: 3

encrypt:
  keystore:
    location: classpath:key/APIKey.jks
    password: ${KEYSTORE_PASSWORD}
    alias: APIKey
